name: Lint and check package version

on:
  - pull_request

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm ci
      - run: npm run lint
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump the version in package.json if this step fails. A new version is needed to publish this package on merge.
        run: |
          git fetch origin main
          git diff origin/main..HEAD -- package.json | grep "+  \"version\": \""
          git diff origin/main..HEAD -- package-lock.json | grep "+  \"version\": \""
