name: Publish to GitHub Packages

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for pushing tags
      packages: write # for publishing packages
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - if: ${{ github.ref_name == 'main' }}
        run: |
          git tag "v$(jq -r .version package.json)"
          git push origin "v$(jq -r .version package.json)"
          echo "publish_tag=latest" >> $GITHUB_ENV
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
